### ISSUE TITLE
SDK releases list or instal problem after v6.0.0

### ISSUE THREAD

**Issue by ecarruda** [tidev/titanium#581]
After updating to v6.0.0 or v6.1.1 commands to list or install sdk releases stopped to work.

Checking it the error is on the 
` 
TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at /usr/local/lib/node_modules/titanium/lib/commands/sdk.js:1457:27
    at Array.find (<anonymous>)
    at Object.getReleases (/usr/local/lib/node_modules/titanium/lib/commands/sdk.js:1456:27)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async errorAsResult (/usr/local/lib/node_modules/titanium/lib/commands/sdk.js:1572:10)
    at async Promise.all (index 0)
    at async Function.list (/usr/local/lib/node_modules/titanium/lib/commands/sdk.js:167:47)
Titanium CLI v6.0.1, https://titaniumsdk.com
Copyright TiDev, Inc. 4/7/2022-Present. All Rights Reserved.
`

**Comment by ecarruda** [comment]
There is an PR already done to solve it.
