### ISSUE TITLE
await... I need some help, please

### ISSUE THREAD

**Issue by sjfigatner** [tidev/titanium#594]
I recently updated my MAC.
Now I get:
[ERROR] Error: Failed to parse /Users/[username]/Documents/Appcelerator_Studio_Workspace/[appname]/node_modules/@babel/helpers/scripts/generate-regenerator-runtime.js
Can not use keyword 'await' outside an async function (6:26)
    at Object.analyzeJs (/Users/[username]/Library/Application Support/Titanium/mobilesdk/osx/11.0.0.GA/node_modules/node-titanium-sdk/lib/jsanalyze.js:115:9)
    at ProcessJsTask.transformAndCopy (/Users/[username]/Library/Application Support/Titanium/mobilesdk/osx/11.0.0.GA/cli/lib/tasks/process-js-task.js:308:31)
    at AndroidBuilder.<anonymous> (/Users/[username]/Library/Application Support/Titanium/mobilesdk/osx/11.0.0.GA/cli/lib/tasks/process-js-task.js:218:17)
    at /usr/local/lib/node_modules/titanium/lib/hook.js:261:13
    at /usr/local/lib/node_modules/titanium/node_modules/async/dist/async.js:3681:19
    at wrapper (/usr/local/lib/node_modules/titanium/node_modules/async/dist/async.js:271:20)
    at replenish (/usr/local/lib/node_modules/titanium/node_modules/async/dist/async.js:441:29)
    at /usr/local/lib/node_modules/titanium/node_modules/async/dist/async.js:451:13
    at eachOfLimit$1 (/usr/local/lib/node_modules/titanium/node_modules/async/dist/async.js:477:34)
    at awaitable (/usr/local/lib/node_modules/titanium/node_modules/async/dist/async.js:211:32)

Might anyone know what I need to do to resolve this?

**Comment by m1ga** [comment]
Please don't post the same error/question in multiple repos. I've replied to the other issue and will close this one.
Thanks
